use crate::prelude::*;
pub(crate) struct TechTypeData {
    pub(crate) what_researches: UnitType,
    pub(crate) order: Order,
    pub(crate) weapon: WeaponType,
    pub(crate) targets_unit: bool,
    pub(crate) required_unit: UnitType,
    pub(crate) research_time: i32,
    pub(crate) targets_position: bool,
    pub(crate) energy_cost: i32,
    pub(crate) what_uses: &'static [UnitType],
    pub(crate) race: Race,
    pub(crate) mineral_price: i32,
    pub(crate) gas_price: i32,
    pub(crate) name: &'static str,
}
pub(crate) static TECH_TYPE_DATA: [TechTypeData; 38] = [
    TechTypeData {
        what_researches: UnitType::Terran_Academy,
        order: Order::None,
        weapon: WeaponType::None,
        targets_unit: false,
        required_unit: UnitType::None,
        research_time: 1200,
        targets_position: false,
        energy_cost: 0,
        what_uses: &[
            UnitType::Terran_Marine,
            UnitType::Terran_Firebat,
            UnitType::Hero_Jim_Raynor_Marine,
            UnitType::Hero_Gui_Montag,
        ],
        race: Race::Terran,
        mineral_price: 100,
        gas_price: 100,
        name: "Stim_Packs",
    },
    TechTypeData {
        what_researches: UnitType::Terran_Covert_Ops,
        order: Order::CastLockdown,
        weapon: WeaponType::Lockdown,
        targets_unit: true,
        required_unit: UnitType::None,
        research_time: 1500,
        targets_position: false,
        energy_cost: 100,
        what_uses: &[
            UnitType::Terran_Ghost,
            UnitType::Hero_Alexei_Stukov,
            UnitType::Hero_Infested_Duran,
            UnitType::Hero_Samir_Duran,
            UnitType::Hero_Sarah_Kerrigan,
        ],
        race: Race::Terran,
        mineral_price: 200,
        gas_price: 200,
        name: "Lockdown",
    },
    TechTypeData {
        what_researches: UnitType::Terran_Science_Facility,
        order: Order::CastEMPShockwave,
        weapon: WeaponType::EMP_Shockwave,
        targets_unit: true,
        required_unit: UnitType::None,
        research_time: 1800,
        targets_position: true,
        energy_cost: 100,
        what_uses: &[UnitType::Terran_Science_Vessel, UnitType::Hero_Magellan],
        race: Race::Terran,
        mineral_price: 200,
        gas_price: 200,
        name: "EMP_Shockwave",
    },
    TechTypeData {
        what_researches: UnitType::Terran_Machine_Shop,
        order: Order::PlaceMine,
        weapon: WeaponType::Spider_Mines,
        targets_unit: false,
        required_unit: UnitType::None,
        research_time: 1200,
        targets_position: true,
        energy_cost: 0,
        what_uses: &[UnitType::Terran_Vulture, UnitType::Hero_Jim_Raynor_Vulture],
        race: Race::Terran,
        mineral_price: 100,
        gas_price: 100,
        name: "Spider_Mines",
    },
    TechTypeData {
        what_researches: UnitType::None,
        order: Order::CastScannerSweep,
        weapon: WeaponType::None,
        targets_unit: true,
        required_unit: UnitType::None,
        research_time: 0,
        targets_position: true,
        energy_cost: 50,
        what_uses: &[UnitType::Terran_Comsat_Station],
        race: Race::Terran,
        mineral_price: 0,
        gas_price: 0,
        name: "Scanner_Sweep",
    },
    TechTypeData {
        what_researches: UnitType::Terran_Machine_Shop,
        order: Order::None,
        weapon: WeaponType::None,
        targets_unit: false,
        required_unit: UnitType::None,
        research_time: 1200,
        targets_position: false,
        energy_cost: 0,
        what_uses: &[
            UnitType::Terran_Siege_Tank_Tank_Mode,
            UnitType::Terran_Siege_Tank_Siege_Mode,
            UnitType::Hero_Edmund_Duke_Tank_Mode,
            UnitType::Hero_Edmund_Duke_Siege_Mode,
        ],
        race: Race::Terran,
        mineral_price: 150,
        gas_price: 150,
        name: "Tank_Siege_Mode",
    },
    TechTypeData {
        what_researches: UnitType::None,
        order: Order::CastDefensiveMatrix,
        weapon: WeaponType::None,
        targets_unit: true,
        required_unit: UnitType::None,
        research_time: 0,
        targets_position: false,
        energy_cost: 100,
        what_uses: &[UnitType::Terran_Science_Vessel, UnitType::Hero_Magellan],
        race: Race::Terran,
        mineral_price: 0,
        gas_price: 0,
        name: "Defensive_Matrix",
    },
    TechTypeData {
        what_researches: UnitType::Terran_Science_Facility,
        order: Order::CastIrradiate,
        weapon: WeaponType::Irradiate,
        targets_unit: true,
        required_unit: UnitType::None,
        research_time: 1200,
        targets_position: false,
        energy_cost: 75,
        what_uses: &[UnitType::Terran_Science_Vessel, UnitType::Hero_Magellan],
        race: Race::Terran,
        mineral_price: 200,
        gas_price: 200,
        name: "Irradiate",
    },
    TechTypeData {
        what_researches: UnitType::Terran_Physics_Lab,
        order: Order::FireYamatoGun,
        weapon: WeaponType::Yamato_Gun,
        targets_unit: true,
        required_unit: UnitType::None,
        research_time: 1800,
        targets_position: false,
        energy_cost: 150,
        what_uses: &[
            UnitType::Terran_Battlecruiser,
            UnitType::Hero_Gerard_DuGalle,
            UnitType::Hero_Hyperion,
            UnitType::Hero_Norad_II,
        ],
        race: Race::Terran,
        mineral_price: 100,
        gas_price: 100,
        name: "Yamato_Gun",
    },
    TechTypeData {
        what_researches: UnitType::Terran_Control_Tower,
        order: Order::None,
        weapon: WeaponType::None,
        targets_unit: false,
        required_unit: UnitType::None,
        research_time: 1500,
        targets_position: false,
        energy_cost: 25,
        what_uses: &[UnitType::Terran_Wraith, UnitType::Hero_Tom_Kazansky],
        race: Race::Terran,
        mineral_price: 150,
        gas_price: 150,
        name: "Cloaking_Field",
    },
    TechTypeData {
        what_researches: UnitType::Terran_Covert_Ops,
        order: Order::None,
        weapon: WeaponType::None,
        targets_unit: false,
        required_unit: UnitType::None,
        research_time: 1200,
        targets_position: false,
        energy_cost: 25,
        what_uses: &[
            UnitType::Terran_Ghost,
            UnitType::Hero_Alexei_Stukov,
            UnitType::Hero_Infested_Duran,
            UnitType::Hero_Samir_Duran,
            UnitType::Hero_Sarah_Kerrigan,
            UnitType::Hero_Infested_Kerrigan,
        ],
        race: Race::Terran,
        mineral_price: 100,
        gas_price: 100,
        name: "Personnel_Cloaking",
    },
    TechTypeData {
        what_researches: UnitType::Zerg_Hatchery,
        order: Order::None,
        weapon: WeaponType::None,
        targets_unit: false,
        required_unit: UnitType::None,
        research_time: 1200,
        targets_position: false,
        energy_cost: 0,
        what_uses: &[
            UnitType::Zerg_Zergling,
            UnitType::Zerg_Hydralisk,
            UnitType::Zerg_Drone,
            UnitType::Zerg_Defiler,
            UnitType::Zerg_Infested_Terran,
            UnitType::Hero_Unclean_One,
            UnitType::Hero_Hunter_Killer,
            UnitType::Hero_Devouring_One,
            UnitType::Zerg_Lurker,
        ],
        race: Race::Zerg,
        mineral_price: 100,
        gas_price: 100,
        name: "Burrowing",
    },
    TechTypeData {
        what_researches: UnitType::None,
        order: Order::CastInfestation,
        weapon: WeaponType::None,
        targets_unit: true,
        required_unit: UnitType::None,
        research_time: 0,
        targets_position: false,
        energy_cost: 0,
        what_uses: &[UnitType::Zerg_Queen, UnitType::Hero_Matriarch],
        race: Race::Zerg,
        mineral_price: 0,
        gas_price: 0,
        name: "Infestation",
    },
    TechTypeData {
        what_researches: UnitType::Zerg_Queens_Nest,
        order: Order::CastSpawnBroodlings,
        weapon: WeaponType::Spawn_Broodlings,
        targets_unit: true,
        required_unit: UnitType::None,
        research_time: 1200,
        targets_position: false,
        energy_cost: 150,
        what_uses: &[UnitType::Zerg_Queen, UnitType::Hero_Matriarch],
        race: Race::Zerg,
        mineral_price: 100,
        gas_price: 100,
        name: "Spawn_Broodlings",
    },
    TechTypeData {
        what_researches: UnitType::None,
        order: Order::CastDarkSwarm,
        weapon: WeaponType::Dark_Swarm,
        targets_unit: true,
        required_unit: UnitType::None,
        research_time: 0,
        targets_position: true,
        energy_cost: 100,
        what_uses: &[UnitType::Zerg_Defiler, UnitType::Hero_Unclean_One],
        race: Race::Zerg,
        mineral_price: 0,
        gas_price: 0,
        name: "Dark_Swarm",
    },
    TechTypeData {
        what_researches: UnitType::Zerg_Defiler_Mound,
        order: Order::CastPlague,
        weapon: WeaponType::Plague,
        targets_unit: true,
        required_unit: UnitType::None,
        research_time: 1500,
        targets_position: true,
        energy_cost: 150,
        what_uses: &[UnitType::Zerg_Defiler, UnitType::Hero_Unclean_One],
        race: Race::Zerg,
        mineral_price: 200,
        gas_price: 200,
        name: "Plague",
    },
    TechTypeData {
        what_researches: UnitType::Zerg_Defiler_Mound,
        order: Order::CastConsume,
        weapon: WeaponType::Consume,
        targets_unit: true,
        required_unit: UnitType::None,
        research_time: 1500,
        targets_position: false,
        energy_cost: 0,
        what_uses: &[
            UnitType::Zerg_Defiler,
            UnitType::Hero_Unclean_One,
            UnitType::Hero_Infested_Kerrigan,
            UnitType::Hero_Infested_Duran,
        ],
        race: Race::Zerg,
        mineral_price: 100,
        gas_price: 100,
        name: "Consume",
    },
    TechTypeData {
        what_researches: UnitType::Zerg_Queens_Nest,
        order: Order::CastEnsnare,
        weapon: WeaponType::Ensnare,
        targets_unit: true,
        required_unit: UnitType::None,
        research_time: 1200,
        targets_position: true,
        energy_cost: 75,
        what_uses: &[
            UnitType::Zerg_Queen,
            UnitType::Hero_Matriarch,
            UnitType::Hero_Infested_Kerrigan,
        ],
        race: Race::Zerg,
        mineral_price: 100,
        gas_price: 100,
        name: "Ensnare",
    },
    TechTypeData {
        what_researches: UnitType::None,
        order: Order::CastParasite,
        weapon: WeaponType::Parasite,
        targets_unit: true,
        required_unit: UnitType::None,
        research_time: 0,
        targets_position: false,
        energy_cost: 75,
        what_uses: &[UnitType::Zerg_Queen, UnitType::Hero_Matriarch],
        race: Race::Zerg,
        mineral_price: 0,
        gas_price: 0,
        name: "Parasite",
    },
    TechTypeData {
        what_researches: UnitType::Protoss_Templar_Archives,
        order: Order::CastPsionicStorm,
        weapon: WeaponType::Psionic_Storm,
        targets_unit: true,
        required_unit: UnitType::None,
        research_time: 1800,
        targets_position: true,
        energy_cost: 75,
        what_uses: &[
            UnitType::Protoss_High_Templar,
            UnitType::Hero_Tassadar,
            UnitType::Hero_Infested_Kerrigan,
        ],
        race: Race::Protoss,
        mineral_price: 200,
        gas_price: 200,
        name: "Psionic_Storm",
    },
    TechTypeData {
        what_researches: UnitType::Protoss_Templar_Archives,
        order: Order::CastHallucination,
        weapon: WeaponType::None,
        targets_unit: true,
        required_unit: UnitType::None,
        research_time: 1200,
        targets_position: false,
        energy_cost: 100,
        what_uses: &[UnitType::Protoss_High_Templar, UnitType::Hero_Tassadar],
        race: Race::Protoss,
        mineral_price: 150,
        gas_price: 150,
        name: "Hallucination",
    },
    TechTypeData {
        what_researches: UnitType::Protoss_Arbiter_Tribunal,
        order: Order::CastRecall,
        weapon: WeaponType::None,
        targets_unit: true,
        required_unit: UnitType::None,
        research_time: 1800,
        targets_position: true,
        energy_cost: 150,
        what_uses: &[UnitType::Protoss_Arbiter, UnitType::Hero_Danimoth],
        race: Race::Protoss,
        mineral_price: 150,
        gas_price: 150,
        name: "Recall",
    },
    TechTypeData {
        what_researches: UnitType::Protoss_Arbiter_Tribunal,
        order: Order::CastStasisField,
        weapon: WeaponType::Stasis_Field,
        targets_unit: true,
        required_unit: UnitType::None,
        research_time: 1500,
        targets_position: true,
        energy_cost: 100,
        what_uses: &[UnitType::Protoss_Arbiter, UnitType::Hero_Danimoth],
        race: Race::Protoss,
        mineral_price: 150,
        gas_price: 150,
        name: "Stasis_Field",
    },
    TechTypeData {
        what_researches: UnitType::None,
        order: Order::None,
        weapon: WeaponType::None,
        targets_unit: true,
        required_unit: UnitType::None,
        research_time: 0,
        targets_position: false,
        energy_cost: 0,
        what_uses: &[UnitType::Protoss_High_Templar],
        race: Race::Protoss,
        mineral_price: 0,
        gas_price: 0,
        name: "Archon_Warp",
    },
    TechTypeData {
        what_researches: UnitType::Terran_Academy,
        order: Order::CastRestoration,
        weapon: WeaponType::Restoration,
        targets_unit: true,
        required_unit: UnitType::None,
        research_time: 1200,
        targets_position: false,
        energy_cost: 50,
        what_uses: &[UnitType::Terran_Medic],
        race: Race::Terran,
        mineral_price: 100,
        gas_price: 100,
        name: "Restoration",
    },
    TechTypeData {
        what_researches: UnitType::Protoss_Fleet_Beacon,
        order: Order::CastDisruptionWeb,
        weapon: WeaponType::Disruption_Web,
        targets_unit: true,
        required_unit: UnitType::None,
        research_time: 1200,
        targets_position: true,
        energy_cost: 125,
        what_uses: &[UnitType::Protoss_Corsair, UnitType::Hero_Raszagal],
        race: Race::Protoss,
        mineral_price: 200,
        gas_price: 200,
        name: "Disruption_Web",
    },
    TechTypeData {
        what_researches: UnitType::None,
        order: Order::None,
        weapon: WeaponType::None,
        targets_unit: false,
        required_unit: UnitType::None,
        research_time: 0,
        targets_position: false,
        energy_cost: 0,
        what_uses: &[],
        race: Race::None,
        mineral_price: 0,
        gas_price: 0,
        name: "Unused_26",
    },
    TechTypeData {
        what_researches: UnitType::Protoss_Templar_Archives,
        order: Order::CastMindControl,
        weapon: WeaponType::Mind_Control,
        targets_unit: true,
        required_unit: UnitType::None,
        research_time: 1800,
        targets_position: false,
        energy_cost: 150,
        what_uses: &[UnitType::Protoss_Dark_Archon],
        race: Race::Protoss,
        mineral_price: 200,
        gas_price: 200,
        name: "Mind_Control",
    },
    TechTypeData {
        what_researches: UnitType::None,
        order: Order::None,
        weapon: WeaponType::None,
        targets_unit: true,
        required_unit: UnitType::None,
        research_time: 0,
        targets_position: false,
        energy_cost: 0,
        what_uses: &[UnitType::Protoss_Dark_Templar],
        race: Race::Protoss,
        mineral_price: 0,
        gas_price: 0,
        name: "Dark_Archon_Meld",
    },
    TechTypeData {
        what_researches: UnitType::None,
        order: Order::CastFeedback,
        weapon: WeaponType::Feedback,
        targets_unit: true,
        required_unit: UnitType::None,
        research_time: 1800,
        targets_position: false,
        energy_cost: 50,
        what_uses: &[UnitType::Protoss_Dark_Archon],
        race: Race::Protoss,
        mineral_price: 100,
        gas_price: 100,
        name: "Feedback",
    },
    TechTypeData {
        what_researches: UnitType::Terran_Academy,
        order: Order::CastOpticalFlare,
        weapon: WeaponType::Optical_Flare,
        targets_unit: true,
        required_unit: UnitType::None,
        research_time: 1800,
        targets_position: false,
        energy_cost: 75,
        what_uses: &[UnitType::Terran_Medic],
        race: Race::Terran,
        mineral_price: 100,
        gas_price: 100,
        name: "Optical_Flare",
    },
    TechTypeData {
        what_researches: UnitType::Protoss_Templar_Archives,
        order: Order::CastMaelstrom,
        weapon: WeaponType::Maelstrom,
        targets_unit: true,
        required_unit: UnitType::None,
        research_time: 1500,
        targets_position: true,
        energy_cost: 100,
        what_uses: &[UnitType::Protoss_Dark_Archon],
        race: Race::Protoss,
        mineral_price: 100,
        gas_price: 100,
        name: "Maelstrom",
    },
    TechTypeData {
        what_researches: UnitType::Zerg_Hydralisk_Den,
        order: Order::None,
        weapon: WeaponType::None,
        targets_unit: false,
        required_unit: UnitType::Zerg_Lair,
        research_time: 1800,
        targets_position: false,
        energy_cost: 0,
        what_uses: &[UnitType::Zerg_Hydralisk],
        race: Race::Zerg,
        mineral_price: 200,
        gas_price: 200,
        name: "Lurker_Aspect",
    },
    TechTypeData {
        what_researches: UnitType::None,
        order: Order::None,
        weapon: WeaponType::None,
        targets_unit: false,
        required_unit: UnitType::None,
        research_time: 0,
        targets_position: false,
        energy_cost: 0,
        what_uses: &[],
        race: Race::None,
        mineral_price: 0,
        gas_price: 0,
        name: "Unused_33",
    },
    TechTypeData {
        what_researches: UnitType::None,
        order: Order::MedicHeal,
        weapon: WeaponType::None,
        targets_unit: true,
        required_unit: UnitType::None,
        research_time: 0,
        targets_position: true,
        energy_cost: 1,
        what_uses: &[UnitType::Terran_Medic],
        race: Race::Terran,
        mineral_price: 0,
        gas_price: 0,
        name: "Healing",
    },
    TechTypeData {
        what_researches: UnitType::None,
        order: Order::None,
        weapon: WeaponType::None,
        targets_unit: false,
        required_unit: UnitType::None,
        research_time: 0,
        targets_position: false,
        energy_cost: 0,
        what_uses: &[],
        race: Race::None,
        mineral_price: 0,
        gas_price: 0,
        name: "None",
    },
    TechTypeData {
        what_researches: UnitType::None,
        order: Order::NukePaint,
        weapon: WeaponType::Nuclear_Strike,
        targets_unit: true,
        required_unit: UnitType::None,
        research_time: 0,
        targets_position: true,
        energy_cost: 0,
        what_uses: &[UnitType::Terran_Ghost],
        race: Race::Terran,
        mineral_price: 0,
        gas_price: 0,
        name: "Nuclear_Strike",
    },
    TechTypeData {
        what_researches: UnitType::Unknown,
        order: Order::Unknown,
        weapon: WeaponType::Unknown,
        targets_unit: false,
        required_unit: UnitType::None,
        research_time: 0,
        targets_position: false,
        energy_cost: 0,
        what_uses: &[],
        race: Race::Unknown,
        mineral_price: 0,
        gas_price: 0,
        name: "Unknown",
    },
];
impl TechType {
    fn d(&self) -> &TechTypeData {
        &TECH_TYPE_DATA[*self as usize]
    }
    pub fn what_researches(&self) -> UnitType {
        self.d().what_researches
    }
    pub fn get_order(&self) -> Order {
        self.d().order
    }
    pub fn get_weapon(&self) -> WeaponType {
        self.d().weapon
    }
    pub fn targets_unit(&self) -> bool {
        self.d().targets_unit
    }
    pub fn required_unit(&self) -> UnitType {
        self.d().required_unit
    }
    pub fn research_time(&self) -> i32 {
        self.d().research_time
    }
    pub fn targets_position(&self) -> bool {
        self.d().targets_position
    }
    pub fn energy_cost(&self) -> i32 {
        self.d().energy_cost
    }
    pub fn what_uses(&self) -> &'static [UnitType] {
        self.d().what_uses
    }
    pub fn get_race(&self) -> Race {
        self.d().race
    }
    pub fn mineral_price(&self) -> i32 {
        self.d().mineral_price
    }
    pub fn gas_price(&self) -> i32 {
        self.d().gas_price
    }
    pub fn name(&self) -> &'static str {
        self.d().name
    }
}
