[build]
# target="i686-pc-windows-msvc"
target="i686-pc-windows-gnu"
# target="x86_64-pc-windows-gnu"

[target.i686-pc-windows-msvc]
linker = "lld"
rustflags = [
  "-Lnative=/home/dante/.xwin/crt/lib/x86",
  "-Lnative=/home/dante/.xwin/sdk/lib/um/x86",
  "-Lnative=/home/dante/.xwin/sdk/lib/ucrt/x86"
]
